include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-(CONFIG_FINGERPRINT_FPC_FULL_FUNCTION) += fpc1020_main.o 
obj-(CONFIG_FINGERPRINT_FPC_FULL_FUNCTION) += fpc1020_common.o 
obj-(CONFIG_FINGERPRINT_FPC_FULL_FUNCTION) += fpc1020_input.o 
obj-(CONFIG_FINGERPRINT_FPC_FULL_FUNCTION) += fpc1020_capture.o 
obj-(CONFIG_FINGERPRINT_FPC_FULL_FUNCTION) += fpc1020_regulator.o


