# ----------------------------------------------------------------------------- 
# export these for cross compiling:
# export ARCH=arm 
# export CROSS_COMPILE=arm-linux-androideabi-
# export KERNELDIR=[path to kernel source]
# ----------------------------------------------------------------------------- 
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y := fpc_irq_main.o 




