obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_FAST_HOTPLUG) 	+= fast_hotplug.o
obj-$(CONFIG_CLUSTER_PLUG)	+= cluster_plug.o
obj-$(CONFIG_INTELLI_PLUG) 	+= intelli_plug.o 
obj-$(CONFIG_BRICKED_HOTPLUG) 	+= bricked_hotplug.o
